- name: Check STCs
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Query a job with a job name of '*'
      zos_job_query:
        job_name: "*"
        job-id: "*"
  
#        - "System Info: {{ result | to_nice_json }}"
#    - name: Return all available z/OS facts.
#      ibm.ibm_zos_core.zos_gather_facts:

#- name: Return z/OS facts in the systems subset ('sys').
#  ibm.ibm_zos_core.zos_gather_facts:
#    gather_subset: sys

