- name: Check STCs
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
  - name: Query a job with a job name of '*'
    ibm.ibm_zos_core.zos_job_query:
       job_name: "*"
    register: result

  - name: Display Host Variables
    ansible.builtin.debug:
      Var: result
    register: time2filt

  - name: Filter the results to job_class.job
    ansible.builtin.set_fact:
      factset: "{{ time2filt.jobs | selectattr('job_class', 'defined') | selectattr('job_class', 'equalto', 'STC') | list }}"
#        - "System Info: {{ result | to_nice_json }}"
#    - name: Return all available z/OS facts.
#      ibm.ibm_zos_core.zos_gather_facts:

#- name: Return z/OS facts in the systems subset ('sys').
#  ibm.ibm_zos_core.zos_gather_facts:
#    gather_subset: sys

