# Writes the JCL inline, submits it, and prints the spool output.
- name: Hello World JCL from local job
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"

  tasks:

  - name: Create a PDS data set if it does not exist
    zos_data_set:
      name: GAMA10.JCL.CNTL3
      type: member  
      space_primary: 15
      space_secondary: 5
      space_type: cyl
      record_format: fb
      record_length: 80
      state: absent
      force: true
    register: job_pds_make
  
  - name: Copy a local file to a PDS member and convert encoding
    zos_copy:
      src: "{{ playbook_dir }}/JCL/hello_world.jcl"
      dest: GAMA10.JCL.CNTL3(HELOWRLD)
      encoding:
        from: UTF-8
        to: IBM-037
    register: write_to_member
    
  - name: Convert local JCL to IBM-037 and submit the job.
    zos_job_submit:
      src: "GAMA10.JCL.CNTL3(HELOWRLD)"
      location: DATA_SET
      wait_time_s: 30
    register: job_sub
    

  - name: Show submit output and return code
    debug:
      var: job_sub

  - name: Show submit output and return code
    debug:
      var: write_to_member

  - name: Show submit output and return code
    debug:
      var: job_pds_make