# Writes the JCL inline, submits it, and prints the spool output.
- name: Hello World JCL from local job
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars:
    hlq: "GAMA10"
    mlq: "JCL"
    llq: "CNTL3"
    member_name: "HELOWRLD"

  tasks:

  - name: Create a PDS data set if it does not exist
    zos_data_set:
      name: "{{ hlq }}.{{ mlq }}.{{ llq }}"
      type: pdse  
      space_primary: 15
      space_secondary: 5
      space_type: cyl
      record_format: fb
      record_length: 80
      state: present
      replace: false
    register: job_pds_make
  
  - name: Copy a local file to a PDS member and convert encoding
    zos_copy:
      src: "{{ playbook_dir }}/JCL/hello_world.jcl"
      dest: "{{ hlq }}.{{ mlq }}.{{ llq }}({{ member_name }})"
      encoding:
        from: UTF-8
        to: IBM-037
    register: write_to_member
    
  - name: Convert local JCL to IBM-037 and submit the job.
    zos_job_submit:
      src: "{{ hlq }}.{{ mlq }}.{{ llq }}({{ member_name }})"
      location: DATA_SET
    register: job_sub
    

  - name: Show submit output and return code
    debug:
      var: job_sub

  - name: Show submit output and return code
    debug:
      var: write_to_member

  - name: Show submit output and return code
    debug:
      var: job_pds_make